fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

git:
    path:  /
    defaults:  { _controller: AppBundle:Git:index }

git_username:
    path:   /{git_username}/comment
    defaults:    { _controller: AppBundle:Git:view }

git_user_check:
    path:  /git_user_check
    defaults:  { _controller: AppBundle:Git:checkUser }

git_repository_check:
    path:   /git_repository_check
    defaults:    { _controller: AppBundle:Git:checkRepository }