stad_line_user:
    resource: "@StadLineUserBundle/Resources/config/routing.yml"
    prefix:   /user

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

login:
    path:   /login
    defaults:  { _controller: StadLineUserBundle:Security:login }

login_check:
    path:   /login_check

logout:
    path:  /logout

git:
    path:  /git
    defaults:  { _controller: AppBundle:Git:index }

git_username:
    path:   /git/{git_username}/comment
    defaults:    { _controller: AppBundle:Git:view }

git_user_check:
    path:  /git_user_check
    defaults:  { _controller: AppBundle:Git:checkUser }

git_repository_check:
    path:   /git_repository_check
    defaults:    { _controller: AppBundle:Git:checkRepository }

homepage:
    path:  /
    defaults:  { _controller: AppBundle:Default:index }